package com.webcollector.webcollector.bean;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.start_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.end_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.car_num
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private String carNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.device_name
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tel
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.battery
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private String battery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mileage
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private String mileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lon
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private Float lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lat
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private Float lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_user
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_user
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.start_time
     *
     * @return the value of user.start_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.start_time
     *
     * @param startTime the value for user.start_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.end_time
     *
     * @return the value of user.end_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.end_time
     *
     * @param endTime the value for user.end_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.car_num
     *
     * @return the value of user.car_num
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public String getCarNum() {
        return carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.car_num
     *
     * @param carNum the value for user.car_num
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setCarNum(String carNum) {
        this.carNum = carNum == null ? null : carNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.device_name
     *
     * @return the value of user.device_name
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.device_name
     *
     * @param deviceName the value for user.device_name
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tel
     *
     * @return the value of user.tel
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tel
     *
     * @param tel the value for user.tel
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.battery
     *
     * @return the value of user.battery
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public String getBattery() {
        return battery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.battery
     *
     * @param battery the value for user.battery
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setBattery(String battery) {
        this.battery = battery == null ? null : battery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mileage
     *
     * @return the value of user.mileage
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public String getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mileage
     *
     * @param mileage the value for user.mileage
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setMileage(String mileage) {
        this.mileage = mileage == null ? null : mileage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lon
     *
     * @return the value of user.lon
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public Float getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lon
     *
     * @param lon the value for user.lon
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setLon(Float lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lat
     *
     * @return the value of user.lat
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lat
     *
     * @param lat the value for user.lat
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_user
     *
     * @return the value of user.create_user
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_user
     *
     * @param createUser the value for user.create_user
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_time
     *
     * @return the value of user.update_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_time
     *
     * @param updateTime the value for user.update_time
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_user
     *
     * @return the value of user.update_user
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_user
     *
     * @param updateUser the value for user.update_user
     *
     * @mbggenerated Sun Mar 01 15:38:07 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}